language: r

sudo: false

install:
  - Rscript -e 'install.packages("optparse")'
  - Rscript -e 'install.packages("httr")'
  - Rscript -e 'install.packages("rjson")'
  - Rscript -e 'install.packages("RCurl")'
  - Rscript -e 'install.packages("RColorBrewer")'

script: Rscript mendeley.R --doi 10.1.1.105.1540
